"""
Top-level Avrae bot command names (and their registered aliases).

An `.alias`/`.snippet` file's body is Avrae command text: any leading word(s)
before a `<drac2>` block or `{{expr}}` name the bot command that the rest of
the alias's output is passed to as arguments (e.g. `embed`, `multiline`).
This is a snapshot of `avrae/avrae`'s directly-registered commands (methods
decorated with `@commands.command()`/`@commands.group()` on the bot itself,
not subcommands of a group like `!cc add`) — used to flag a likely-typo'd
leading command. Re-derive from the avrae source if this drifts.
"""
from __future__ import annotations

KNOWN_LEADING_COMMANDS: frozenset[str] = frozenset(
    {
        "2",
        "a",
        "about",
        "action",
        "admin",
        "attack",
        "avatar",
        "background",
        "bestiary",
        "beyond",
        "br",
        "c",
        "campaign",
        "cast",
        "cc",
        "changelog",
        "changepresence",
        "char",
        "character",
        "charref",
        "check",
        "class",
        "classfeat",
        "commandstats",
        "condition",
        "csettings",
        "customcounter",
        "cvar",
        "ddb",
        "ddb-debug",
        "dderror",
        "desc",
        "dicecloud",
        "echo",
        "embed",
        "feat",
        "g",
        "game",
        "globalvar",
        "gsheet",
        "gvar",
        "i",
        "import",
        "info",
        "init",
        "invite",
        "item",
        "iterroll",
        "lookup_settings",
        "ma",
        "mc",
        "mcast",
        "monattack",
        "moncast",
        "moncheck",
        "monimage",
        "monsave",
        "monster",
        "monster_attack",
        "monster_cast",
        "monster_check",
        "monster_save",
        "ms",
        "multiline",
        "multiroll",
        "name",
        "pack",
        "ping",
        "pingall",
        "playertoken",
        "portrait",
        "prefix",
        "pythag",
        "r",
        "race",
        "racefeat",
        "randchar",
        "randname",
        "reference",
        "roll",
        "rollstats",
        "rr",
        "rrr",
        "rule",
        "s",
        "save",
        "sb",
        "server_settings",
        "servervar",
        "servsettings",
        "sheet",
        "show_join_message",
        "species",
        "speciesfeat",
        "spell",
        "spellbook",
        "stats",
        "status",
        "subclass",
        "svar",
        "techo",
        "tembed",
        "test",
        "token",
        "tome",
        "transferchar",
        "tutorial",
        "update",
        "uservar",
        "uvar",
    }
)
